### PR TITLE
hotfix: I added 'npm install -g pnpm' in Dockerfile

### PR DESCRIPTION
**Pull request by LorenzoLopezz**
To verify the performance, I modified the code and ran the docker cleanly, from start to finish.

### CODE REVIEW

**Comment by AykutSarac** [comment]
Do you think this will fix #375?

**Comment by LorenzoLopezz** [comment]
> Do you think this will fix #375?

Yes, the report is about the same thing.

**Comment by johnny9144** [comment]
I think using `corepack` to initiate `pnpm` is better.

here is what `Dockerfile` with `corepack` looks like

```
# Builder
FROM node:18-alpine as builder
RUN corepack enable
WORKDIR /src

# Cache dependencies first
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# Copy other files and build
COPY . /src/
RUN pnpm build

# App
FROM nginxinc/nginx-unprivileged
COPY --chown=nginx:nginx --from=builder /src/out /app
COPY default.conf /etc/nginx/conf.d/default.conf

```

only adding `RUN corepack enable` before `pnpm install` is enough.

**Comment by AykutSarac** [comment]
@johnny9144 can you open a PR for that?

**Pull request closed without merging**
