### PR TITLE
Add fallback to alignChildren sort to ensure correct order

### LINKED ISSUE #340: [BUG]: Error rendering view when there is attribute after a array attribute
### Issue description

Input json:
```json
{
  "foo": 123,
  "bar": "123",
  "authorities": [
    1,
    2,
    3
  ],
  "context": null
}
```
The `foo` `bar` attribute is not rendering correctly.

图片

But When I remove the `context` attibute, works fine.

图片

### Media & Screenshots

_No response_

### Operating system

- OS: Windwos 10
- Browser: Firefox 115.0.2

### Priority this issue should have

High (immediate attention needed)

### PR DESCRIPTION
**Pull request by Eldemarkki**
Fixes #340

### CODE REVIEW

**Comment by AykutSarac** [comment]
How does that solve the problem?

**Comment by Eldemarkki** [comment]
To be honest I don't really know. I noticed that the `.sort` method produced different results on Chrome and Firefox, indicating that the comparison function was not stable. Unstable sorting can be fixed by adding more logic to the comparison function and that's what I did. 

I tested with many different inputs and they all worked, so this shouldn't break anything.

**Review by MarisV — APPROVED** [review]

**Comment by Eldemarkki** [comment]
Looks like this has been fixed, I assume in [this change](https://github.com/AykutSarac/jsoncrack.com/commit/0e35c6a1e9f6ef211321cfdd28e4e8abfa0106e7#diff-f73b1987f60d565e71febc131684db5680e6a256a8d8ed4fcc949ae2b8ba60ee), so I'll close this PR.

**Comment by AykutSarac** [comment]
> Looks like this has been fixed, I assume in [this change](https://github.com/AykutSarac/jsoncrack.com/commit/0e35c6a1e9f6ef211321cfdd28e4e8abfa0106e7#diff-f73b1987f60d565e71febc131684db5680e6a256a8d8ed4fcc949ae2b8ba60ee), so I'll close this PR.

No, this commit improves type support only. We can keep this open.

**Comment by Eldemarkki** [comment]
@AykutSarac That other change has some logic changes too:

image
and
image

**Comment by Eldemarkki** [comment]
Nevermind my other comment, it's still a bit broken so this PR is still needed. I'll check those merge conflicts tomorrow.

**Comment by Eldemarkki** [comment]
@AykutSarac any updates? I've fixed the merge conflicts.

**Comment by aboutZZ** [comment]
https://github.com/AykutSarac/jsoncrack.com/issues/340 Any updates?

**Pull request closed without merging**
