### PR TITLE
#257 Getting path of JSON on clicking the edges

### PR DESCRIPTION
**Pull request by hanbin9775**
Feature implementation of issue #257

When edges are clicked, modal popup.
Implementation looks like below.

image

The modal shows only path not content of node.
Node contents are able to view by clicking individual nodes.

### CODE REVIEW

**Comment by AykutSarac** [comment]
Great work, thank you! There seem to be some bugs to be fixed, I've tried with this JSON and I couldn't get the path from right most edges. https://api.opensource.org/licenses/permissive

**Comment by hanbin9775** [comment]
Thanks for reporting the bug. It seems the new feature doesn't work well if root node is not a single object.
I will try to fix the code as soon as possible.

**Comment by hanbin9775** [comment]
Fixed the bug that didn't work well when root data is array.
It works well with the [https://api.opensource.org/licenses/permissive](https://api.opensource.org/licenses/permissive) now

**Comment by AykutSarac** [comment]
Improved algorithm performance and made some changes.

**Pull request merged**
