### PR TITLE
Feature Edit JSON in Diagram View 

### PR DESCRIPTION
**Pull request by theogainey**
## Description 

Edit JSON in Diagram View 
- Enable editing JSON in graph nodes
- Add Invalid JSON error to graph node modal containers
- Add graph parser function to parse nodes into JSON  

References Issue #147

### CODE REVIEW

**Comment by theogainey** [comment]
I updated this PR to work with the recent changes

**Comment by AykutSarac** [comment]
I've edited the "powers" key and it gotten a really weird structure. You've made an amazing work, but I think we should keep the PR open for a while for others to contribute to it. Graph to JSON is really hard and hard to implement because the parsing algorithm is also should be working perfectly to do the reverse parsing.

**Comment by theogainey** [comment]
@AykutSarac All that makes sense. Do you mind describing the weird behavior you're seeing so I can take a look at it. Also if there are any specific issues with the original parser that could use some work I would be interested in taking a look at it. This is cool project and I am planning on continuing to contribute to it if I can.

**Comment by AykutSarac** [comment]
Thanks for your interest in contributing @theogainey that's awesome! #27 and #51 are the highest priority issues of the parser exists since the first release. You can take a look to them if you have any idea on how to fix them.

**Comment by AykutSarac** [comment]
Converting this PR to draft as it's currently not ready but could be improved and implemented in future.

**Comment by iolh** [comment]
了不起！期待早日上线。

It's amazing and I'm looking forward to it.

**Comment by NielsKorschinsky** [comment]
Please see #262 for additional ideas/options

**Comment by AykutSarac** [comment]
Thanks for your efforts, closing this PR as there's a better way to implement this using the Path to Node data.

**Pull request closed without merging**
