### PR TITLE
#198 add copy node path to clipboard

### PR DESCRIPTION
**Pull request by eLeontev**
**Issue:** #198 

**Reason:** feature request

**Changes:**
- update selected node to select NodeData instead of it's text (the whole node is stored as selected instead of only it's text property)
- add UI button in the modal which repeats the same copyToClipboard funcitonality, but use different content
- use `getParentsForNodeId` to get list of parent nodes based on official API https://reaflow.dev/?path=/story/docs-utils-graph--page#parent-node-traversal
-  add util to form path to node in readable string format

**Known limitations:**
 - cannot provide path based on array index (e.g. path[2].prop is not achievable, instead it would be `path.prop`)

**Result:**
copy path

### CODE REVIEW

**Comment by AykutSarac** [comment]
Currently it returns the nodes data from clipboard, however it supposed to return data of nodes.

**Comment by eLeontev** [comment]
> Currently it returns the nodes data from clipboard, however it supposed to return data of nodes.

Hey, not sure if I got the point. Could you clarify that need to be changed?

I understood it to use`text` property from each node (as in clipboard funcitonality) ineastead of whole node. Am I right?

**Comment by AykutSarac** [comment]
The author of the issue actually mentioned the [expected behaviour,](https://github.com/AykutSarac/jsoncrack.com/issues/198#issuecomment-1272575955) if you still would like to work on it I will keep the PR open.

**Comment by eLeontev** [comment]
thanks, I'll take a look.

**Comment by AykutSarac** [comment]
Thanks for the PR, I'm closing this as it's outdated compared to current version but we can still consider adding this in the future.

**Pull request closed without merging**
