### PR TITLE
fix empty nodes

### PR DESCRIPTION
**Pull request by victorbrambati**
I created the PR #242 but the updates created a conflict with my old PR. This PR solve the same problem, I tested the problems from #242 and it work correctly. Thank you for the patience.

### CODE REVIEW

**Comment by AykutSarac** [comment]
It works so great, thanks so much for that I'll be following up and testing this! Would you be able to make improvements for this to work? #181

**Comment by victorbrambati** [comment]
> It works so great, thanks so much for that I'll be following up and testing this! Would you be able to make improvements for this to work? #181

Yes I create it now, but to not bug all UI of graph I put it only in objects out of an array, I don't know if the PR #181 is better choose, but to you compare I printed the graph:

Result of #181:
image
`{
  _id: "generated",
  field: "value",
  object: {
    fieldA: "valA",
    ObjectNestA: {
      fieldNestA: "valB",
    },
  },
}`

Result of the first example in #242:

image
`
{
  "properties": {
    "definitions": {
      "type": "object",
      "additionalProperties": {
        "$dynamicRef": "#meta"
      },
      "deprecated": true
    }
  }
}
`

You want that I push this commit?

**Comment by AykutSarac** [comment]
Yes, please push the commit. II'll test it with more data and share my feedbacks with you.

**Comment by AykutSarac** [comment]
There's this issue, if there is a single object. The fields with string should be in a single node and rest should be connected to it. From this JSON it works very different that you will notice:

```json
{
  "id": "AAL",
  "identifiers": [
    {
      "identifier": "AAL",
      "scheme": "SPDX"
    },
    {
      "identifier": "License :: OSI Approved :: Attribution Assurance License",
      "scheme": "Trove"
    }
  ],
  "links": [
    {
      "note": "OSI Page",
      "url": "https://opensource.org/licenses/AAL"
    }
  ],
  "name": "Attribution Assurance License",
  "other_names": [],
  "superseded_by": null,
  "keywords": [
    "osi-approved",
    "discouraged",
    "redundant"
  ],
  "text": [
    {
      "media_type": "text/html",
      "title": "HTML",
      "url": "https://opensource.org/licenses/AAL"
    }
  ]
}
```

How it looks in the PR:
image

How it should look:
image

I'm guessing it happens because nodes are created right after a line is read and not until whole object is did read?
You can compare PR with the existing version using the following json: https://api.opensource.org/licenses/

Thanks again for putting your effort into this, you will make a significant impact on this project :)

**Comment by AykutSarac** [comment]
For example for the default json, if I move one line to bottom the view changes:
image

```json
{
  "squadName": "Super hero squad",
  "homeTown": "Metro City",
  "formed": 2016,
  "secretBase": "Super tower",
  "members": [
    {
      "name": "Molecule Man",
      "age": 29,
      "secretIdentity": "Dan Jukes",
      "powers": [
        "Radiation resistance",
        "Turning tiny",
        "Radiation blast"
      ]
    },
    {
      "name": "Madame Uppercut",
      "age": 39,
      "secretIdentity": "Jane Wilson",
      "powers": [
        "Million tonne punch",
        "Damage resistance",
        "Superhuman reflexes"
      ]
    },
    {
      "name": "Eternal Flame",
      "age": 1000000,
      "secretIdentity": "Unknown",
      "powers": [
        "Immortality",
        "Heat Immunity",
        "Inferno",
        "Teleportation",
        "Interdimensional travel"
      ]
    }
  ],
  "active": true
}
```

**Comment by AykutSarac** [comment]
Looks like when a parent node is collapsed and its parent is collapsed and expanded back, it's child disappears. Should be investigated later on after the parser is setup.

**Comment by victorbrambati** [comment]
About this issue, is to create a single node with fields with string that does not have a parent? (in the first layer of JSON)

**Comment by victorbrambati** [comment]
> Looks like when a parent node is collapsed and its parent is collapsed and expanded back, it's child disappears. Should be investigated later on after the parser is setup. This PR will make #161 possible sparkles

Amazing! :sparkles:

**Comment by AykutSarac** [comment]
> About this issue, is to make it too to fields with string that have parents? Because your example only have nodes that not have a parent. Example:
> 
> ```
> {
>   "one": {
>     "sa": "sa",
>     "si": "si",
>     "right": {
>       "example": "example"
>     },
>     "cg": "Cg"
>   }
> }
> ```
> 
> "sa": "sa", "si": "si" and "cg": "Cg" is to be the same node or "cg": "Cg" is to be separated of others in other node?

No, what I mean here is when going through inside of an object e.g. 
```json
{
  "str1": "string",
  "array": ["hi", "ho"],
  "str2": "string2"
}
```

String values inside of an object should create a single object and rest should be seperated and connected same as how current jsoncrack.com works.

How it is:
image

How it should be:
image

**Comment by victorbrambati** [comment]
> Can you elaborate with example of data? I think with the latest commit all seems fine.

Yes, the commit [76bcad4](https://github.com/AykutSarac/jsoncrack.com/pull/251/commits/76bcad4e1d8ce6e213b0f85de41da8c0ad1dc752) kept separated the brothers node in a object from array.

This example was obtained in: https://api.opensource.org/licenses/

`[
  {
    "id": "AAL",
    "identifiers": [
      {
        "identifier": "AAL",
        "scheme": "SPDX"
      },
      {
        "identifier": "License :: OSI Approved :: Attribution Assurance License",
        "scheme": "Trove"
      }
    ],
    "links": [
      {
        "note": "OSI Page",
        "url": "https://opensource.org/licenses/AAL"
      }
    ],
    "name": "Attribution Assurance License",
    "other_names": [],
    "superseded_by": null,
    "keywords": [
      "osi-approved",
      "discouraged",
      "redundant"
    ],
    "text": [
      {
        "media_type": "text/html",
        "title": "HTML",
        "url": "https://opensource.org/licenses/AAL"
      }
    ]
  },
  {
    "id": "AFL-3.0",
    "identifiers": [
      {
        "identifier": "AFL-3.0",
        "scheme": "SPDX"
      },
      {
        "identifier": "License :: OSI Approved :: Academic Free License (AFL)",
        "scheme": "Trove"
      }
    ],
    "links": [
      {
        "note": "OSI Page",
        "url": "https://opensource.org/licenses/AFL-3.0"
      }
    ],
    "name": "Academic Free License, Version 3.0",
    "other_names": [],
    "superseded_by": null,
    "keywords": [
      "osi-approved",
      "discouraged",
      "redundant"
    ],
    "text": [
      {
        "media_type": "text/html",
        "title": "HTML",
        "url": "https://opensource.org/licenses/AFL-3.0"
      }
    ]
  }
]`

commit [76bcad4](https://github.com/AykutSarac/jsoncrack.com/pull/251/commits/76bcad4e1d8ce6e213b0f85de41da8c0ad1dc752):

image

new commit [e772153](https://github.com/AykutSarac/jsoncrack.com/pull/251/commits/e772153cd3b250bb734baef786fd07dfc1d69f43):
image

**Comment by victorbrambati** [comment]
Now with the last commit [e772153](https://github.com/AykutSarac/jsoncrack.com/pull/251/commits/e772153cd3b250bb734baef786fd07dfc1d69f43)  all seems fine.

**Comment by AykutSarac** [comment]
Thank you Victor! Finally, I believe it would be a better UX experience to not have a root node if there's an array of object at root level independent of each other like in the https://api.opensource.org/licenses/

So, same as the current version can we keep them seperated without connections?

```json
[
  {
    "id": "Zlib",
    "identifiers": [
      {
        "identifier": "Zlib",
        "scheme": "DEP5"
      },
      {
        "identifier": "Zlib",
        "scheme": "SPDX"
      },
      {
        "identifier": "License :: OSI Approved :: zlib/libpng License",
        "scheme": "Trove"
      }
    ],
    "links": [
      {
        "note": "OSI Page",
        "url": "https://opensource.org/licenses/Zlib"
      }
    ],
    "name": "The zlib/libpng License (Zlib)",
    "other_names": [],
    "superseded_by": null,
    "keywords": [
      "osi-approved"
    ],
    "text": [
      {
        "media_type": "text/html",
        "title": "HTML",
        "url": "https://opensource.org/licenses/Zlib"
      }
    ]
  },
  {
    "id": "jabberpl",
    "identifiers": [
      {
        "identifier": "License :: OSI Approved :: Jabber Open Source License",
        "scheme": "Trove"
      }
    ],
    "links": [
      {
        "note": "OSI Page",
        "url": "https://opensource.org/licenses/jabberpl"
      }
    ],
    "name": "Jabber Open Source License",
    "other_names": [],
    "superseded_by": null,
    "keywords": [
      "discouraged",
      "retired",
      "osi-approved"
    ],
    "text": [
      {
        "media_type": "text/html",
        "title": "HTML",
        "url": "https://opensource.org/licenses/jabberpl"
      }
    ]
  }
]
```

image

**Comment by victorbrambati** [comment]
@AykutSarac Yes. I will commit now.

**Comment by AykutSarac** [comment]
Awesome work @victorbrambati! Parser seems ready to be merged, now I'm investigate the collapse/expand issue and I'll commit whenever I find a solution. You may want to take a look if you have an idea.

```json
{
  "ankara": {
    "name": "name",
    "username": "username",
    "password": "password",
    "servers": [
      {
        "ipaddress": "10.10.10.10",
        "listenport": 4222,
        "clusterport": 6112
      }
    ]
  }
}
```

**Comment by victorbrambati** [comment]
> Awesome work @victorbrambati! Parser seems ready to be merged, now I'm investigate the collapse/expand issue and I'll commit whenever I find a solution. You may want to take a look if you have an idea.
> 
> ```json
> {
>   "ankara": {
>     "name": "name",
>     "username": "username",
>     "password": "password",
>     "servers": [
>       {
>         "ipaddress": "10.10.10.10",
>         "listenport": 4222,
>         "clusterport": 6112
>       }
>     ]
>   }
> }
> ```

It happen when a parent connect a parent directly, before that did not happen. Probrably is a problem in algorithm of a collapsed nodes that it was not thought to work in these circumstances.

**Comment by victorbrambati** [comment]
@AykutSarac I found a solution:

**Comment by AykutSarac** [comment]
Awesome work @victorbrambati, I'm merging this now with the `main` branch 🚀

**Comment by AykutSarac** [comment]
Awesome work @victorbrambati, I'm merging this now with the `main` branch 🚀

**Pull request merged**
