### PR TITLE
Added 'url' query parameter for loading JSON files.

### PR DESCRIPTION
**Pull request by VladCuciureanu**
Solves #149

This adds a way to load JSON files via the 'url' query parameter

Example:
`/editor?url=http://ip.jsontest.com/`

### CODE REVIEW

**Comment by VladCuciureanu** [comment]
> Can we make it to work on Widget page too? Also can we use fetch API instead of XMLHttpReqeust for more general convention?

Done :)

**Comment by AykutSarac** [comment]
Can we add a loading state and display the `<Loading />` component while fetching data? (considering the fetch failing case)

**Comment by VladCuciureanu** [comment]
> Can we add a loading state and display the `<Loading />` component while fetching data? (considering the fetch failing case)

Is something like [this](https://github.com/AykutSarac/jsoncrack.com/pull/229/commits/77705503481f0b2034ed84453ae57e73d146eaaa) what you had in mind?

**Comment by AykutSarac** [comment]
> > Can we add a loading state and display the `<Loading />` component while fetching data? (considering the fetch failing case)
> 
> Is something like [this](https://github.com/AykutSarac/jsoncrack.com/pull/229/commits/77705503481f0b2034ed84453ae57e73d146eaaa) what you had in mind?

I couldn't view the link you sent but what I meant is similar to when you paste big json and it display's "Parsing JSON" screen. You can test it with https://www.reddit.com/r/all.json

**Comment by VladCuciureanu** [comment]
Should be good then.

**Comment by victorbrambati** [comment]
> Solves #149
> 
> This adds a way to load JSON files via the 'url' query parameter
> 
> Example: `/editor?url=http://ip.jsontest.com/`

I create it in a  PR #70 , but it is closed. You can test it [here](https://jsonvisio-com-sigma.vercel.app/editor).

**Comment by VladCuciureanu** [comment]
@AykutSarac I'm ok with either impl so it's up to you

**Comment by AykutSarac** [comment]
> @AykutSarac I'm ok with either impl so it's up to you

I'm not a fan of creating new states honestly, so I'd go for this one as it's more up to date. Have you added the loading state yet?

**Comment by VladCuciureanu** [comment]
> > @AykutSarac I'm ok with either impl so it's up to you
> 
> 
> 
> I'm not a fan of creating new states honestly, so I'd go for this one as it's more up to date. Have you added the loading state yet?

Yep. Ready for review/merge

**Comment by AykutSarac** [comment]
Thanks for working on it, however this implementation does not satisfy with project and breaks its mechanism at some point, I think it's mostly because it does not have a proper documentation. I'll handle this at a new PR, thanks for the contribution! 🙂

**Pull request closed without merging**
